# Generated by Django 4.1.7 on 2023-03-11 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_alter_recipefavorite_recipe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recipeincludeingredients',
            options={'ordering': ('ingredient',), 'verbose_name': 'Ингредиент для рецепта', 'verbose_name_plural': 'Ингредиенты для рецепта'},
        ),
    ]
