# Generated by Django 4.1.7 on 2023-03-13 07:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingredients', '0002_alter_ingredient_measurement_unit'),
        ('recipes', '0004_alter_recipeincludeingredients_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cooking_time',
            field=models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1, 'Не менее 1 минуты')], verbose_name='Время приготовления (минуты) рецепта'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='recipes.RecipeIncludeIngredients', to='ingredients.ingredient', verbose_name='Ингредиенты рецепта'),
        ),
    ]
